добавила разметку, стили и частично логику для страницы MonthReportView
alex-shepel/kapusta pull request #5
Opened 2022-01-15 18:20 UTC by Sv0707

2022-01-15 20:52 UTC, alex-shepel requested changes

2022-01-15 20:52 UTC, alex-shepel commented on src/components/IncomesExpenseList/IncomesExpenseList.js
> +        </div>
Почему не оформила однотипные элементы в виде списка `<ul>`?

2022-01-15 20:52 UTC, alex-shepel commented on src/components/IncomesExpenseList/IncomesExpenseList.js
> +// import { useDispatch } from 'react-redux';
Закомментированный код лучше не оставлять.

2022-01-15 20:52 UTC, alex-shepel commented on src/components/IncomesExpenseList/IncomesExpenseList.js
> +import IncomesExpenseListItem from '../IncomesExpenseListItem/IncomesExpenseListItem';
Мы юзаем `index.js` дле реэкспорта. Чтобы не дублировать имя компоненты дважды:  `IncomesExpenseListItem/IncomesExpenseListItem`. Также благодаря настройке `jsconfig.json` мы не используем относительные пути с двумя точками `../`. Если выполнишь эти рекоммендации путь будет `components/IncomesExpenseListItem`. Такой путь будет независим от положения твоей компоненты в дереве проекта. Повышаеться легкость переиспользования. Также это будет соответствовать командному стилю.

2022-01-15 20:52 UTC, alex-shepel commented on src/components/IncomesExpenseListItem/IncomesExpenseListItem.jsx
> +import imageDelete from '../../images/delete.svg';
То же самое. Путь можно заменить на `images/delete.svg`. Это все еще будет работать.

2022-01-15 20:52 UTC, alex-shepel commented on src/components/IncomesExpenseList/IncomesExpenseList.js
> +  operationSign,
Добавь `prop-types`.

2022-01-15 20:52 UTC, alex-shepel commented on src/components/IncomesExpenseListItem/IncomesExpenseListItem.jsx
> +  operationSign,
Не описала `prop-types`.

2022-01-15 20:52 UTC, alex-shepel commented on src/components/IncomesExpenseListItem/IncomesExpenseListItem.module.css
> +  color: #52555f;
Цвета есть в переменных в `:root`. Нужно заюзать оттуда. Если твоих цветов нет, можно смело дописать свои :)

2022-01-15 20:52 UTC, alex-shepel commented on src/components/IncomesExpenseListItem/IncomesExpenseListItem.module.css
> +@media screen and (max-width: 250px) {
Размер экрана стартует с `320px`. Зачем такое медиа правило?

2022-01-15 20:52 UTC, alex-shepel commented on src/views/MonthReportView/MonthReportView.jsx
> +import IncomesExpenseList from 'components/IncomesExpenseList/IncomesExpenseList';
Тоже нужно поправить после добавления `index.js`.

2022-01-15 20:52 UTC, alex-shepel commented on src/views/MonthReportView/MonthReportView.jsx
> +              {' '}
Нужно удалить. Может вылезть где-то, где не звали :)

2022-01-16 08:04 UTC, Sv0707 commented on src/components/IncomesExpenseList/IncomesExpenseList.js
> +  operationSign,
Добавила

2022-01-16 08:04 UTC, Sv0707 commented on src/components/IncomesExpenseListItem/IncomesExpenseListItem.jsx
> +import imageDelete from '../../images/delete.svg';
+

2022-01-16 08:04 UTC, Sv0707 commented on src/components/IncomesExpenseListItem/IncomesExpenseListItem.jsx
> +  operationSign,
Добавила

2022-01-16 08:04 UTC, Sv0707 commented on src/views/MonthReportView/MonthReportView.jsx
> +import IncomesExpenseList from 'components/IncomesExpenseList/IncomesExpenseList';
Исправила

2022-01-16 09:33 UTC, alex-shepel approved these changes

2022-01-16 09:34 UTC, merged